#+TITLE:    LDSC-ProjetoEngenharia-0-Metodologia-Instrucoes-Etapas

* Link:

- O repositório https://github.com/ldsc/LDSC-ProjetoEngenharia-0-Metodologia-Instrucoes-Etapas contém informações sobre a metodologia adotada no desenvolvimento do projeto de engenharia.

- Este arquivo que você esta lendo contém:
  - um resumo da metodologia adotada.
  - uma lista de repositórios e projetos desenvolvidos em anos anteriores.

* Versão: 
- 1.0.

* Data:
- 2024/1 - primeiro semestre.
  
* Autor de Contato:
- André Duarte Bueno
- [[mailto:andreduartebueno@gmail.com][andreduartebueno@gmail.com]]
- [[mailto:bueno@lenep.uenf.br][bueno@lenep.uenf.br]]

* Áreas de pesquisa vinculadas:
- Modelagem Computacional (Algoritmos).
- Modelagem de Software (UML).
- Programação Orientada a Objeto.
- Programação em C++.
- Programação Paralela e Concorrente.
- Engenharia de Petróleo.
- Gestão de Projetos de Engenharia (métodos tradicionais e ágeis).
- Administração (gestão de projetos e processos).

* Disciplinas vinculadas:
- [[https://sites.google.com/view/professorandreduartebueno/ensino/fundamentos-de-programa%C3%A7%C3%A3o-em-c][Disciplina Fundamentos de Ciência da Computação]].
- [[https://sites.google.com/view/professorandreduartebueno/ensino/introdu%C3%A7%C3%A3o-ao-projeto-de-engenharia][Disciplina Introdução ao Projeto de Engenharia]].
- [[https://sites.google.com/view/professorandreduartebueno/ensino/prog-orientada-objeto-c-2024][Disciplina Programação Orientada a Objeto com C++]].
- [[https://sites.google.com/view/professorandreduartebueno/ensino/projeto-de-software-aplicado][Disciplina Projeto de Software Aplicado]].
- [[https://sites.google.com/view/professorandreduartebueno/ensino/programa%C3%A7%C3%A3o-paralela-e-concorrente][Disciplina Programação Paralela e Concorrente]].
    
* Links:
- [[https://sites.google.com/view/professorandreduartebueno/][Site do Professor André Duarte Bueno]].
- [[https://github.com/ldsc][Site do *LDSC - Laboratório de Desenvolvimento de Software Científico e Aplicado* no github]].
- [[https://uenf.br/cct/lenep][Site do LENEP]].

* Resumo da metodologia

A metodologia irá cobrir as etapas para o desenvolvimento de um projeto de engenharia completo.
Fazemos uma relação com o conceito de Nível de Maturidade Tecnológica ou TRL.
O TRL é utilizado nos projetos da Petrobras (os desafios tecnológicos da Petrobras).

Etapas: 
0 - O professor ou empresa de engenharia elabora um desafio tecnológico ([[https://docs.google.com/forms/d/e/1FAIpQLSc1NaIUvKIFzECj3KPv6JRiD7kXFFd5MeAY1w-JI_yDjrbZmQ/viewform][formulário desafio tecnológico]]).
Uma lista de desafios é apresentada nesta [[https://docs.google.com/spreadsheets/d/1mFAjcRhzuePATaSSUSYo3_JaVmPkIi0L7ZfrQe0MMSU/edit?usp=sharing][planilha]].
Uma lista de projetos antigos é apresentada ao longo deste documento.

1 - A equipe de alunos seleciona o projeto de seu interesse e elabora um pré-projeto (um esboço); Este pré-projeto é então levado ao professor/empresa que montou o desafio e ao professor da disciplina para aprovarem o pré-projeto.  A ideia aqui é ter certeza que os alunos entenderam o que o professor/empresa quer.

2- Os alunos montam o projeto (detalhamento do pré-projeto; documento formal que descreve o que vai ser feito).
Ex: os contratos de projeto que assinamos com a Petrobras.

3- Os alunos fazem a modelagem de engenharia com acompanhamento dos professores.

4- Os alunos desenvolvem o software em si (ciclos de planejamento/refinar a modelagem; implementar os códigos; realizar testes; montar a documentação).

5- Entrega/defesa do produto final.


* Lista de Repositórios do LDSC
Veja a seguir uma lista de repositórios do LDSC, estão disponíveis repositórios com informações em geral, modelos de documentos e projetos, exemplos de projetos desenvolvidos em anos anteriores.

* <<1>>Repositórios com instruções e modelos
** Título: UENF-CCT-LENEP-Repositorio-Documentos
- Link no github:
  - https://github.com/ldsc/UENF-CCT-LENEP-Repositorio-Documentos
- Resumo:
  - Arquivos da UENF, CCT, LENEP para apoio a alunos.
- Área:
  - Administrativa.

** Título: LDSC-Ajuda-DocumentosAuxiliares
- Link no github:
  - https://github.com/ldsc/LDSC-Ajuda-DocumentosAuxiliares
- Resumo:
  - Informações sobre softwares e sistemas utilizados nas disciplinas de modelagem computacional do LENEP/CCT/UENF.
- Área:
  - Modelagem computacional.

** Título: LDSC-ProjetoEngenharia-0-Metodologia-Instrucoes-Etapas
- Link no github:
  - https://github.com/ldsc/LDSC-ProjetoEngenharia-0-Metodologia-Instrucoes-Etapas
- Resumo:
  - Repositório com informações sobre a metodologia adotada no desenvolvimento do projeto de engenharia vinculado as disciplinas de modelagem computacional.
- Área:
  - Modelagem computacional.

** Título: LDSC-ProjetoEngenharia-1-PropostaDeDesafio-TituloDoDesafioTecnologico
- Link no github:
  - https://github.com/ldsc/LDSC-ProjetoEngenharia-1-PropostaDeDesafio-TituloDoDesafioTecnologico
- Resumo:
  - Repositório com modelo de proposta de desafio tecnológico.
  - A proposta de desafio tecnológico pode ser feita por professores e profissionais da indústria (empresas).
- Área:
  - Modelagem computacional.
  - Engenharia de petróleo.

** Título: LDSC-ProjetoEngenharia-2-Software-TituloProjeto-ModeloCompleto
- Link no github:
  - https://github.com/ldsc/LDSC-ProjetoEngenharia-2-Software-TituloProjeto-ModeloCompleto
- Resumo:
  - Modelo de projeto de engenharia (usado a partir de 2024/1 cobrindo as disciplinas de modelagem computacional).
  - Inclui um conjunto de diretórios e arquivos dos softwares utilizados (ex.: modelos do lyx, umbrello).
- Área:
  - Projeto de engenharia.
  - Modelagem computacional.
  - Engenharia de petróleo.

** Título: LDSC-ProjetoEngenharia-2-Software-TituloProjeto-ModeloAntigoDesativado
- Link no github:
  - https://github.com/ldsc/LDSC-ProjetoEngenharia-2-Software-TituloProjeto-ModeloAntigoDesativado
- Resumo:
  - Modelo de projeto de engenharia (usado até 2023/2).
  - Não incluia a parte de gestão (metodologia, desafio tecnológico, pré-projeto e projeto).

** Título: LDSC-Modelo-TrabalhoAcademico-01-OrganizacaoPessoal
- Link no github:
  - https://github.com/ldsc/LDSC-Modelo-TrabalhoAcademico-01-OrganizacaoPessoal
- Resumo:
  - Repositório com modelo de arquivo do lyx para confecção do trabalho acadêmico que visa ajudar na organização pessoal dos novos alunos.
  - Usado por alunos de Introdução à Engenharia.
- Área:
  - Ensino.
  - Gestão pessoal.

** Título: LDSC-Modelo-TrabalhoAcademico-02-ArquivoUnico
- Link no github:
  - https://github.com/ldsc/LDSC-Modelo-TrabalhoAcademico-02-ArquivoUnico
- Resumo:
  - Repositório com modelo de arquivo do lyx para confecção do trabalho acadêmico de pequeno porte usando o editor LyX.
- Área:
  - Ensino.

** Título: LDSC-Modelo-DiretorioAlunoBolsista-TCC-IC-MSC-DSC-Projeto
- Link no github:
  - https://github.com/ldsc/LDSC-Modelo-DiretorioAlunoBolsista-TCC-IC-MSC-DSC-Projeto
- Resumo:
  - Diretório com subdiretórios e arquivos para alunos de IC, MSC, DSC. Inclui modelos para TeX/LaTeX/LyX.
- Área:
  - Metodologia científica.
  - Organização/gestão pessoal.
* <<2>>Repositórios de bibliotecas desenvolvidas

** Título: Biblioteca lib_ldsc
- Link no github:
  - https://github.com/ldsc/lib_ldsc
- Resumo:
  - A libldsc é uma biblioteca de classes desenvolvidas em C++ para solução de problemas das áreas de:
  - processamento de imagens.
  - meios porosos (rochas reservatório).
  - métodos numéricos.
  - grafos, redes de percolação e redes neurais.
  - O software [[https://github.com/ldsc/lvp][Software LVP]] faz uso extensivo da lib_ldsc.
  - Manual técnico: [[https://github.com/ldsc/lib_ldsc/blob/master/doc/ManualTecnico/Doutorado-AndreDuarteBueno.pdf][Tese doutorado Prof. André Duarte Bueno]]
  - Apresentação:  [[https://github.com/ldsc/lib_ldsc/blob/master/doc/ManualTecnico/ApresentacaoLinhaPesquisaAnaliseDeImagens-ProcParalelo-Bueno-2023-reduzida.pdf][Apresentação linhas de pesquisa que usam a lib_ldsc]]
- Área:
  - Análise e processamento de imagens.
* <<3>>Repositórios de softwares desenvolvidos

** Título: Software LVP - Laboratório Virtual de Petrofísica
- Link no github:
  - https://github.com/ldsc/lvp
- Resumo:
  - O software LVP oferece ao usuário diversas funcionalidades de simulação e determinação de propriedades petrofísicas através da análise de imagens de meios porosos. O propósito inicial no desenvolvimento deste software foi o de facilitar, através de uma interface gráfica amigável e avançada, a utilização dos modelos e algoritmos desenvolvidos como parte de um trabalho de mestrado, e posteriormente de doutorado, realizado na UENF/LENEP pelo aluno Leandro Puerari. Devido ao fato dos trabalhos terem como base a biblioteca para análise de imagens de meios porosos lib_ldsc, diversas outras funcionalidades implementadas nesta biblioteca foram disponibilizadas no LVP.
  - Dentre as funcionalidades podemos destacar:
  - Aplicação de filtros em imagens 2D e 3D, incluindo: conectividade, imagem de distância ao fundo, inversão da imagem, passa-baixa e passa-alta;
  - Aplicação dos filtros morfológicos: fechamento, abertura, dilatação e erosão;
  - Visualização plano a plano de imagens tridimensionais permitindo escolher o eixo de visualização;
  - Visualização de imagens tridimensionais e bidimensionais;
  - Determinação de correlações frequencial e espacial;
  - Determinação da distribuição de tamanho de poros e sólidos;
  - Cálculo da permeabilidade intrínseca; 
  - Cálculo da permeabilidade relativa;
  Visualização das curvas de permeabilidade relativa;
  - Visualização dos gráficos de correlações;
  - Cálculo da porosidade;
  - Rotação de imagens tridimensionais;
  - Corte de imagens tridimensionais;
  - Determinação das configurações de equilíbrio;
  - Reconstruções tridimensionais através dos métodos esferas sobrepostas, gaussiana truncada e gaussiana truncada revisada;
  - Segmentação de poros e gargantas, através de operações morfológicas;
  - Criação de redes de percolação representativas ao meio poroso;
  - Cálculo da permeabilidade intrínseca nas redes de percolação.
  - Autor: Leandro Puerari.
- Área:
  - Análise e processamento de imagens.

** Título: Simulat - Simulador Transferência Calor e Massa em Meios Porosos
- Link no github:
  - https://github.com/ldsc/simulat
- Resumo:
  - Simulador Transferência Calor e Umidade em Telhas Cerâmicas (meios porosos).
  - A partir de propriedades físicas medidas em laboratório permite a simulação dos valores de conteúdo mássico e temperatura de telhas expostas ao meio ambiente.
  - [[https://github.com/ldsc/simulat/blob/master/doc/ManualTecnico/Mestrado-AndreDuarteBueno.pdf][Mestrado-AndreDuarteBueno.pdf]].
  - [[https://github.com/ldsc/simulat/blob/master/doc/ManualTecnico/Mestrado-AndreDuarteBueno-Apresentacao.pdf][Mestrado-AndreDuarteBueno-Apresentacao.pdf]].    
  - [[https://github.com/ldsc/simulat/blob/master/doc/ManualTecnico/Mestrado-AndreDuarteBueno-ImagensSoftwareSimulat.pdf][ImagensSoftwareSimulat]].
- Área:
  - Transferência de calor e massa.
  - Conforto ambiental.

** Título: Software-CaracterizacaoDeRochaDigitalUsando-IA-InteligenciaArtificial-SegmentacaoImagens
- Link no github:
  - https://github.com/ldsc/Software-CaracterizacaoDeRochaDigitalUsando-IA-InteligenciaArtificial-SegmentacaoImagens
- Resumo:
  - Este repositório representa o projeto de dissertação desenvolvido no LENEP/CCT/UENF, como parte das exigências para obtenção do título de Mestre em Engenharia de Reservatório e de Exploração.
  - O objetivo geral deste trabalho foi desenvolver métodos de inteligência artificial capazes de reconhecer padrões relevantes para a análise das propriedades petrofísicas em imagens de rochas reservatórios.
  - No diretório resultados estão os valores obtidos na aplicação da rede neural sobre às amostras de rocha digital junto com o resultado da binarização de cada um delas.
  - Autor: João Marcelo.
- Área:
  - Análise e processamento de imagens. 

** Título: SAIL - Software de Análise de Imagens Livre
- Link no github:
  - adicionar...
- Resumo:
  - Software de Análise de Imagens Livre.
  - Autor: Thiago Schauwer.
- Área:
  - Análise e processamento de imagens.
  - Dano a formação.
  - Engenharia de reservatório.
  - Petrofísica.

** Título: TCMP-2D
- Link no github:
  - https://github.com/ldsc/TCMP-2D
- Resumo:
  - Transferência de Calor em Meios Porosos 2D (Linguagem: C++/Qt; Método Numérico: FTCS/BTCS).
  - Autor: Guilherme Lima.
  - Publicação:
    - [[https://github.com/ldsc/TCMP-2D/blob/master/doc/ManualTecnico/ProjetoEngenharia-GuilhermeLima.pdf][TCC]] 
    - [[https://github.com/ldsc/TCMP-2D/blob/master/doc/ManualTecnico/R3-SimuladorBidimensionaldeConducaoTransientedeCaloremMeiosPorosos-CCMP-2D.pdf][SimuladorBidimensionaldeConducaoTransientedeCaloremMeiosPorosos-CCMP-2D]]

- Área:
  - Transferência de calor.

** Título: ProjetoEngenharia-STC-3D-SimuladorDeTransferenciaDeCalor-3D
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-STC-3D-SimuladorDeTransferenciaDeCalor-3D
- Resumo:
  - Projeto de engenharia - Simulador de condução térmica em objetos 3D com perfis genéricos.
  - O seguinte projeto de engenharia deve simular a difusão térmica de qualquer objeto tridimensional, onde o usuário desenha a superfície de alguns perfis e escolhe as temperaturas e suas propriedades termofísicas.
  - A equação do Calor será modelada por diferenças finitas pelo modelo BTCS, utilizando fronteiras de Neumann, e a programação utilizará paralelismo e multithreading para acelerar as simulações.
  - No quesito prático, o usuário poderá desenhar a superfície a ser simulada, escolher sua temperatura, propriedades termofísicas e se é fonte/sumidouro ou não. Também terá a liberdade de escolher um ponto para analisar os gráficos da evolução térmica no tempo e espaço, salvar as superfícies dos perfis e carregar essas camadas com todas as suas propriedades e modificá-las. Por fim, o projeto será utilizado para estudar a injeção de calor em reservatórios 2D e 3D, e avaliar a distribuição da temperatura ao longo do tempo no reservatório.
  - Nota: Também foi o TCC do aluno Nikolas.    
- Área:
  - Transferência de calor.
- Autor:
  - Nikolas Almeida Pinto.
  - Publicação:
    - [[https://github.com/ldsc/ProjetoEngenharia-STC-3D-SimuladorDeTransferenciaDeCalor-3D/blob/master/doc/ManualTecnico/TCC-NikolasAlmeidaPinto.pdf][TCC]] 
    - [[https://github.com/ldsc/ProjetoEngenharia-STC-3D-SimuladorDeTransferenciaDeCalor-3D/blob/master/doc/ManualTecnico/Apresentacao_Nicholas_TCC2.pptx][Apresentacao]]
- 
* <<4>>Repositórios de projetos desenvolvidos

** Título: ProjetoEngenharia-AnaliseDoEfeitoDePeliculaAPartirIPR-PocosVerticais-EscoamentoMonofasico
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-AnaliseDoEfeitoDePeliculaAPartirIPR-PocosVerticais-EscoamentoMonofasico
- Resumo:
  - ANÁLISE DO EFEITO DE PELÍCULA A PARTIR DE CURVAS DE ÍNDICE DE PRODUTIVIDADE (IPR) PARA POÇOS VERTICAIS EM ESCOAMENTO MONOFÁSICO DE ÓLEO.
  - Utilizar equações propostas na literatura e em artigos cientı́ficos para o cálculo do efeito de pelı́cula total.
  - Plotar curvas de IPR para poços verticais em escoamento monofásico de óleo a partir de soluções analı́ticas da E.D.H. considerando regime transiente, pseu-do permanente e permanente a partir do software externo Gnuplot.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-AnaliseQuedaPressaoDevidoMigracaoFinosOcasionadaInjecaoAguaBaixaSalinidade
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-AnaliseQuedaPressaoDevidoMigracaoFinosOcasionadaInjecaoAguaBaixaSalinidade
- Resumo:
  - ANÁLISE DA QUEDA DE PRESSÃO DEVIDO A MIGRAÇÃO DE FINOS OCASIONADA PELA INJEÇÃO DE ÁGUA DE BAIXA SALINIDADE.
  - Desenvolver um projeto de Engenharia de Software que calcule a quantidade de partículas depositadas no meio poroso devido a migração de finos, utili- zando como dados/informações de referência os valores da literatura ou de experimentos laboratoriais, os quais serão inseridos pelo usuário por meio de arquivos .txt. Por meio do software será possível analisar o declínio de perme- abilidade, ou seja o dano à formação, devido a quantidade de partículas retidas no meio poroso e assim evitar prejuízos ecônomicos as indústrias petróliferas, pois será possível realizar uma análise e um estudo prévio do caso.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-AplicacaoCorrelacoesCalculoParametrosReservartorioPropriedadesFluidos-Blackoil
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-AplicacaoCorrelacoesCalculoParametrosReservartorioPropriedadesFluidos-Blackoil
- Resumo:
  - DESENVOLVIMENTO DO SOFTWARE APLICAÇÃO DE CORRELAÇÕES PARA CÁLCULO DE PARÂMETROS DE RESERVATÓRIO A PARTIR DE PROPRIEDADES DOS FLUIDOS – MODELAGEM BLACKOIL.
  - Utilizar correlações empı́ricas para cálculo de parâmetros de um reservatório a partir de propriedades dos fluidos presentes no mesmo – Modelagem BlackOil. – Calcular propriedades dos fluidos a partir de dados externos. – Calcular parâmetros de um reservatório utilizando correlações especı́ficas.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-AutomacaoDaDefinicaoDoVolumeElementarRepresentativo
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-AutomacaoDaDefinicaoDoVolumeElementarRepresentativo
- Resumo:
  - O PetroRev é um software desenvolvido em C++ que automatiza o processo de análise de Volume Elementar Representativo (REV) de amostras rochosas digitalizadas por microtomografia de raios X. Esse processo é crucial para determinar um volume estatisticamente representativo para simulações em escala de poros, especialmente focando na propriedade petrofísica da porosidade.
  - Pré-processamento de Imagens: Prepara as imagens de microtomografia para análise.
  - Segmentação e Identificação de Poros e Sólidos: Identifica áreas porosas e não porosas nas imagens.
  - Cálculo de Porosidade em Subamostras: Calcula a porosidade de subamostras para determinar o REV.
  - Análise Estatística para Identificação do REV: Utiliza dados de porosidade para determinar um volume representativo estatisticamente.
- Área:
  - Petrofísica.

** Título: ProjetoEngenharia-AvaliacaoCondicaoExperimentalSeparacaoComponentesDoPetroleoPorCromatografiaLiquida
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-AvaliacaoCondicaoExperimentalSeparacaoComponentesDoPetroleoPorCromatografiaLiquida
- Resumo:
  - Em desenvolvimento.
- Área:
  - Geoquímica.

** Título: ProjetoEngenharia-AvaliacaoDasCondicoesExperimentaisParaSeparacaoDeComponentesDoPetroleoPorCromatogr
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-AvaliacaoDasCondicoesExperimentaisParaSeparacaoDeComponentesDoPetroleoPorCromatogr
- Resumo:
  - AVALIAÇÃO DAS CONDIÇÕES EXPERIMENTAIS PARA SEPARAÇÃO DE COMPONENTES DO PETRÓLEO POR CROMATOGRAFIA LÍQUIDA UTILIZANDO PLANEJAMENTO FATORIAL.
  - Determinar, a partir do planejamento fatorial com ponto central, as melhores condições experimentais para a obtenção da fração de hidrocarbonetos satura- dos do petróleo utilizando a técnica de cromatografia em fase líquida clássica em coluna aberta, visando diminuir a quantidade de solvente e adsorvente utilizado, aumentar a porcentagem de recuperação da fração e, como conse- quência, reduzir a quantidade de resíduos líquidos e sólidos gerados ao meio ambiente.
- Área:
  - Geoquímica.

** Título: ProjetoEngenharia-AvaliacaoFormacoesPorDadosDeTestesDePressao
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-AvaliacaoFormacoesPorDadosDeTestesDePressao
- Resumo:
  - AVALIAÇÃO DE FORMAÇÕES POR DADOS DE TESTES DE PRESSÃO.
  - Criar um software capaz de fornecer ao usuário parâmetros e características do reservatório, através da análise dos dados obtidos em testes de pressão em poços, possibilitando estimar as dimensões do campo e sua potencialidade econômica.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-BancoDeDadosFluidosPerfuracao
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-BancoDeDadosFluidosPerfuracao
- Resumo:
  - BANCO DE DADOS DE FLUIDOS DE PERFURAÇÃO.
  - Desenvolver um banco de dados contendo informações a respeito defluidos de perfuração desenvolvidos no Laboratório de Fluidos do LENEP-Laboratório de Engenharia e Exploração de Petróleo.
- Área:
  - Engenharia de poço.

** Título: ProjetoEngenharia-CalculoDaTrajetoriaDirecionalParaperfuracaoDePocosDePetroleo-TIPO-1-BUILD-AND-HOLD
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-CalculoDaTrajetoriaDirecionalParaperfuracaoDePocosDePetroleo-TIPO-1-BUILD-AND-HOLD
- Resumo:
  - CÁLCULO DE TRAJETÓRIA DIRECIONAL PARA PERFURAÇÃO DE POÇOS DE PETRÓLEO: TIPO 1 - BUILD AND HOLD.
  - Desenvolver uma solução para o cálculo da trajetória em 2D de um projeto de poço vertical e direcional.
- Área:
  - Engenharia de poço.

** Título: ProjetoEngenharia-CalculoDosFatoresDeRecuperacaoAvancadaDePetroleoAPartirDeTesteDeFluxoEmMeiosPoroso
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-CalculoDosFatoresDeRecuperacaoAvancadaDePetroleoAPartirDeTesteDeFluxoEmMeiosPoroso
- Resumo:
  - CÁLCULO DOS FATORES DE RECUPERAÇÃO AVANÇADA DE PETROLEO À PARTIR DE TESTES DE FLUXO EM MEIO POROSO.
  - Calcular a permeabilidade absoluta de amostras rochosas;
  - Obter grfico da permeabilidade absoluta da amostra (plugs );
  - Calcular o volume poroso de amostras rochosas;
  - Calcular as frações de recuperação de óleo a partir do método utilizado: Secundário e/ou Avançado;
  - Possibilitar a inclusão de informações de novosfuidos e amostras (plugs );
  - Obter gráficos com as curvas de produção de água e de óleo através da recuperaçao secundária e avançada a partir da entrada de dados pelo usuário (volumes produzidos por minuto);
  - Obter as saturações iniciais e finais dos fluidos injetados no meio poroso;
  - Obter o fator de recuperação total de óleo através dos métodos de recuperação utilizados.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-CalculoIndiceProdutividadePocos
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-CalculoIndiceProdutividadePocos
- Resumo:
  - Desenvolver um projeto de engenharia de software para resolver os diferentes modelos matemáticos de previsão de produtividade de poços horizontais e ver- ticais e a influência dos parâmetros de reservatórios nos mesmos para analisar em que situações, em termos de produtividade, qual design de poço seria mais recomendado através das simulações.
- Área:
  - Engenharia de poço.

** Título: ProjetoEngenharia-CalculoPerdaCargaDistribuidaFluidoNoDecorrerEscoamento
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-CalculoPerdaCargaDistribuidaFluidoNoDecorrerEscoamento
- Resumo:
  - CÁLCULO DA PERDA DE CARGA DISTRIBUIDA DE UM FLUIDO NO DECORRER DO ESCOAMENTO.
  - Desenvolver um projeto de engenharia de software para calcular a perda de carga distribuída de um fluido no decorrer do escoamento ao longo da tubulação.
- Área:
  - Engenharia de elevação e escoamento.
  - Engenharia de poço.

** Título: ProjetoEngenharia-CalculoVolumesFluidosPerfuracaoCimentacaoTubosETempoPerfuracao
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-CalculoVolumesFluidosPerfuracaoCimentacaoTubosETempoPerfuracao
- Resumo:
  - Desenvolver um programa para cálculo dos volumes de fluido de perfuração e cimento, quantidade de tubos e o tempo gasto em uma operação de perfuração de um poço de petróleo.
- Área:
  - Engenharia de poço.

** Título: ProjetoEngenharia-CorrelacoesPVT
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-CorrelacoesPVT
- Resumo:
  - Criar um banco virtual de correlações onde seja possível estimar diversas propriedades relacionadas ao gás e ao óleo presentes em um reservatório. Visando a empregá-lo no ensino e pesquisa.
- Área
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-ESPPERFORMANCE-SimuladorDeCurvasDeDesempenhoDe-BCS-HEAD-ePerdasCarga
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-ESPPERFORMANCE-SimuladorDeCurvasDeDesempenhoDe-BCS-HEAD-ePerdasCarga
- Resumo:
  - ESPPERFORMANCE - SIMULADOR DE CURVAS DE DESEMPENHO DE BCS: HEAD E PERDAS DE CARGA.
  - Desenvolver um simulador que calcule as curvas de perfomance de operação de BCS utilizado em elevação artficial de petróleo a partir de parametrizações para escoamento defluidos em bombas centrífugas.
- Área:
  - Engenharia de elevação e escoamento.

** Título: ProjetoEngenharia-FluxoMonofasicoReativoEmMeiosPorosos
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-FluxoMonofasicoReativoEmMeiosPorosos
- Resumo:
  - Em desenvolvimento.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-ModelosDeAquiferosAnaliticos
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-ModelosDeAquiferosAnaliticos
- Resumo:
  - MODELOS DE AQUÍFEROS ANALÍTICOS.
  - No ambiente da Engenharia de Reservatórios, o objeto de estudo é o próprio reservatório de óleo e gás. No entanto, para que esse estudo ocorra de forma eficiente, é necessário que se entenda as características (porosidade, permeabilidade, volume de reservatório, presença e propriedades de aquíferos) e o comportamento sob produção. O objetivo de estudo deste software é analisar aquíferos analíticos com modelos distintos e como sua presença provoca efeitos em reservatórios de óleo e gás.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-ModelosDeDeslocamentoImiscivelParaRecuperacaoSecundariaDePetroleo
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-ModelosDeDeslocamentoImiscivelParaRecuperacaoSecundariaDePetroleo
- Resumo:
  - MODELOS DE DESLOCAMENTO IMISCÍVEL PARA RECUPERAÇÃO SECUNDÁRIA DE PETRÓLEO.
  - O projeto a ser desenvolvido consiste em um programa que calculará características de um reservatório homogêneo a partir de um fluxo bifásico areal, preverá o desempenho no processo de recuperação secundária do óleo a partir de um sistema estratificado com fluxo bifásico. A presente construção do sistema será utilizado em âmbito acadêmico como software livre, a partir do uso da Programação Orientada a Objeto em C++ e software Gnuplot, para que esteja disponível de fácil acesso a todos. A interface selecionada para o programa é em modo texto, o usuário irá se relacionar a partir do uso do teclado, mouse e monitor em conjunto com a interface do sistema construído. Os dados de entrada, propriedades do reservatório, serão fornecidos em modo .xlsx, na qual poderá ser modificado pelo usuário com base nas informações do reservatório em questão, enquanto que os dados de saída serão em modo arquivo de texto .txt e imagem .png com base nos diferentes modelos de deslocamento possíveis do software.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-PrevisaoComportamentoDeReservatoriosDeOleoComCapaDeGasOuGasEmSolucaoEOleo-GasComIn
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-PrevisaoComportamentoDeReservatoriosDeOleoComCapaDeGasOuGasEmSolucaoEOleo-GasComIn
- Resumo:
  - PREVISÃO DE COMPORTAMENTO DE RESERVATÓRIOS DE ÓLEO COM CAPA DE GÁS OU GÁS EM SOLUÇÃO E ÓLEO & GÁS COM INFLUXO DE ÁGUA.
  - Desenvolver um software para determinar os parâmetros comportamentais de um reservatório de óleo com capa de gás para a caracterização desse reservatório por meio da análise e cálculos a partir de dados de produção.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-PropriedadesFisicasRochasSedimentaresUtilizandoDadosObtidosPorAnaliseDeImagens
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-PropriedadesFisicasRochasSedimentaresUtilizandoDadosObtidosPorAnaliseDeImagens
- Resumo:
  - DETERMINAÇÃO DE PROPRIEDADES FÍSICAS DE ROCHAS SEDIMENTARES UTILIZANDO DADOS OBTIDOS POR ANÁLISE DE IMAGENS DIGITAIS.
  - Desenvolver um software que receba dados obtidos do ImageJ e converta-os em caracterização da rocha em análise.
  - As novas atualizações foram a inclusão de classes como: Analise porosidade, Parametros Morfometricos, Propriedades rocha (homogeneidade e heterogeneidade), Metodo RbSr, Volume representativo do elemento (REV) e SimulacaoFluxoFluidos (liquido e gasoso).
- Área:
  - Petrofísica.

** Título: ProjetoEngenharia-SimulacaoDeCurvasIPRUtilizandoModelosEmpiricosEmPocosVerticais
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SimulacaoDeCurvasIPRUtilizandoModelosEmpiricosEmPocosVerticais
- Resumo:
  - SIMULADOR DE CURVAS IPR UTILIZANDO MODELOS EMPÍRICOS EM POCOS VERTICAIS.
  - Selecionar o tipo de fluido e geometria do reservatório.
  - Desenvolver os cálculos das vazões e pressões com base nos modelos empíricos (Fetkovich, Vogel, Vogel Generalizada e Linear). – Plotar gráficos e permitir que possam ser salvos. – Permitir que o usuário possa entrar com os dados por meio de um arquivo de disco.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-SimulacaoPropriedadesTermodinamicasSubstanciasSimplesECompostas
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SimulacaoPropriedadesTermodinamicasSubstanciasSimplesECompostas
- Resumo:
  - SIMULAÇÃO DE PROPRIEDADES TERMODINÂMICAS DE SUBSTÂNCIAS SIMPLES E COMPOSTAS.
  - bter propriedades termodinâmicas de substâncias simples e misturas de substâncias. Estas propriedades incluem fugacidade, densidade, volume específico, volume molar, e o fator de compressibilidade, tanto da fase líquida, quanto da fase vapor (se as duas coexistirem).
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-SimuladorDeEstimativaDeReservaUtilizandoEBM-EnfoqueReservatoriosGas
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SimuladorDeEstimativaDeReservaUtilizandoEBM-EnfoqueReservatoriosGas
- Resumo:
  - SIMULADOR DE ESTIMATIVA DE RESERVA DE RESERVATÓRIO UTILIZANDO EBM, COM ENFOQUE NOS RESERVATÓRIOS DE GÁS.
  - Aperfeiçoar a solução para determinar o volume original de fluido (principalmente gás) no reservatório, incluindo a modelagem de diferentes mecanismos de produção e a injeção de fluidos.
  - Implementar classes e métodos para representar a injeção de água, gás, polímero, surfactante, vapor e gás lift no reservatório.
  - Aprimorar a flexibilidade do programa para lidar com uma variedade de cenários de produção e injeção.
  - Refinar a lógica de cálculo do volume original de fluido para considerar os efeitos das novas classes de injeção.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-SimuladorDeReservatorioMonofasico2D
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SimuladorDeReservatorioMonofasico2D
- Resumo:
  - SIMULADOR DE RESERVATÓRIO MONOFÁSICO 2D.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-SimuladorDeTracoSismico
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SimuladorDeTracoSismico
- Resumo:
  - Desenvolver um programa para a gerar um traço sísmico sintético de uma formação arbitrária a partir de dados da formação com espessura da camada, velocidade de propagação da onda acústica e a densidade.
- Área:
  - Geofísica.

** Título: ProjetoEngenharia-SimuladorHidraulicaPerfuracaoPoco
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SimuladorHidraulicaPerfuracaoPoco
- Resumo:
  - Desenvolver um simulador de hidráulica de poço que execute cálculos e gere gráficos. Para tal, deve-se usar as equações de perda de carga provenientes da mecânica dos fluidos adaptadas à indústria do petróleo.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-SimuladorPropriedadesMaterialSubmetidoCorrosaoPorDioxidoDeCarbono
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SimuladorPropriedadesMaterialSubmetidoCorrosaoPorDioxidoDeCarbono
- Resumo:
  - Simulador de Propriedades Mecânicas de Material Submetido ao Processo de Corrosão por Dióxido de Carbono. Desenvolver um programa que receba dados reais ou arbitrários e calcule as propriedades mecânicas do material a partir de onde serão gerados gráficos que poderão ser utilizados para análise de taxas corrosivas.
- Área:
  - Corrosão.

** Título: rojetoEngenharia-SimuladorReservatorio2D
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SimuladorReservatorio2D
- Resumo:
  - Em desenvolvimento.
  - Criar um software capaz de fornecer ao usuário parâmetros e características do reservatório, através da análise dos dados obtidos em testes de pressão em poços, possibilitando estimar as dimensões do campo e sua potencialidade econômica.
  - Nota: Continuidade do projeto: https://github.com/ldsc/ProjetoEngenharia-SimuladorDeReservatorioMonofasico2D
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-SimuladorSolucoesAnaliticasAdmensionaisEqDifusividadeHidraulicaFluxosLinearERadial
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SimuladorSolucoesAnaliticasAdmensionaisEqDifusividadeHidraulicaFluxosLinearERadial
- Resumo:
  - SIMULADOR DE SOLUÇÕES ANALÍTICAS ADIMENSIONAIS DA EQUAÇÃO DA DIFUSIVIDADE HIDRÁULICA PARA FLUXOS LINEAR E RADIAL.
  - A partir da descoberta de uma acumulação de petróleo diversas informações podem ser obtidas. Das mais importantes, pode-se citar como exemplo a quantidade de hidro- carbonetos que se pode retirar dessa jazida e o tempo em que essa produção se efetuará. Dentro da engenharia de petróleo, engenheiros de reservatório constantemente buscam solucionar problemas envolvendo fluxos monofásicos de fluidos de baixa compressibilidade que partem das as equações fundamentais da mecânica dos fluidos que descrevem o trans- porte de líquidos em meios porosos. A principal equação que rege esse estudo do fluxo em meios porosos é a Equação da Difusividade Hidráulica e ao resolver os problemas de valor inicial e de contorno formados por essa equação, é possível obter os modelos físicos de interesse que são encontrados no campo. A necessidade de monitoramento do comportamento do reservatório é evidente e prever como será o seu comportamento auxilia diretamente na tomada de decisões a respeito das operações realizadas e serve de base para os testes de pressão que visam a obtenção de vários parâmetros do reservatório (fator de película, volume poroso drenado, limites do reservatório, etc).
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-SimuladorSubstituicaoFluidoEmodelagemAVO
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SimuladorSubstituicaoFluidoEmodelagemAVO
- Resumo:
  - DESENVOLVIMENTO DO SOFTWARE SIMULADOR DE SUBSTITUIÇÃO DE FLUIDOS E DE MODELAGEM AVO.
  - Realizar a substituição de fluidos para plotar um gráfico de velocidade da onda compressional pela saturação de água e de velocidade da onda cisalhante pela saturação de água.
- Área:
  - Geofísica

** Título: ProjetoEngenharia-SoftwareCaracterizacaoDeReservatoriosIntegradoAAnalisePetrofisica
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SoftwareCaracterizacaoDeReservatoriosIntegradoAAnalisePetrofisica
- Resumo:
  - DESENVOLVIMENTO DO SOFTWARE CARACTERIZAÇÃO DE RESERVATÓRIOS INTEGRADO À ANÁLISE PETROFÍSICA.
  - Criar um software capaz de calcular parâmetros e inferir características de um reservatório, através da análise dos dados obtidos em testes de pressão em poços e na testemunhagem do reservatório, possibilitando estimar as dimensões do campo e sua potencialidade econômica. Um diferencial importante nesta versão é a flexíbilidade na entrada de dados do usuário.
- Área:
  - Petrofísica.

** Título: ProjetoEngenharia-SoftwareControlador-MedidorDeBancadaAz-pH-mV-ORP-Cond-TDS-SALT
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SoftwareControlador-MedidorDeBancadaAz-pH-mV-ORP-Cond-TDS-SALT
- Resumo:
  - Em desenvolvimento.
- Área:
  - Equipamentos de laboratório.

** Título: rojetoEngenharia-SoftwareDeComunicacao-MedidorLCR
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SoftwareDeComunicacao-MedidorLCR
- Resumo:
  - Em desenvolvimento.
- Área:
  - Equipamentos de laboratório.

** Título: ProjetoEngenharia-SoftwareParaCalculoDeIncrustacaoNaProducaoDePetroleo
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SoftwareParaCalculoDeIncrustacaoNaProducaoDePetroleo
- Resumo:
  - Em desenvolvimento.
- Área:
  - Engenharia de reservatório.
  - Petrofísica.

** Título: ProjetoEngenharia-SoftwareParaCalculoDePropriedadesReologicasDeFluidosDePerfuracao
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SoftwareParaCalculoDePropriedadesReologicasDeFluidosDePerfuracao
- Resumo:
  - Faltando esta informação.
- Área:
  - Engenharia de poço.

** Título: ProjetoEngenharia-SoftwareParaTratamentosDeDados-FT-ICR-MS-e-Aplica-esGeoquimicas
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SoftwareParaTratamentosDeDados-FT-ICR-MS-e-Aplica-esGeoquimicas
- Resumo:
  - Software para tratamentos de dados FT-ICR MS e aplicações geoquímicas.
  - Facilitar o uso da petroleômica.
  - Calcular o número de carbono, hidrogênio e nitrogênio.
  - Calcular a distribuição heteroatômica para cada amostra.
  - Calcular o número de DBE e sua distribuição para cada classe heteroatômica.
  - Calcular a distribuição do número de carbono por DBE para cada classe hete- roatômica.
  - Calcular parâmetros geoquímicos com os dados petroleômicos. – Plotar gráficos e diagramas.
- Área:
  - Geoquímica.

** Título: ProjetoEngenharia-SoftwareQueCalculaPropriedadesPetrofisicasPocoAPartirEquacoesDaFisica
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SoftwareQueCalculaPropriedadesPetrofisicasPocoAPartirEquacoesDaFisica
- Resumo:
  - ProjetoEngenharia-SoftwareQueCalculaPropriedadesPetrofisicasPocoAPartirEquacoesDaFisica.
  - Plotar os perfis.
  - Calcular a porosidade.
  - Calcular a argilosidade.
  - Calcular a saturação de óleo e água.
  - Plotar as propriedades calculadas.
- Área:
  - Petrofísica.

** Título: ProjetoEngenharia-SPTSP-Helmholtz
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SPTSP-Helmholtz
- Resumo:
  - SIMULADOR DE PROPRIEDADES TERMODINÂMICAS DE SUBSTÂNCIAS PURAS A PARTIR DE DENSIDADE E TEMPERATURA.
  - A correta previsão das propriedades termodinâmicas e cálculo do equilíbrio de fases constitui-se num ponto fundamental do projeto de qualquer processo da industria química, como sistemas de refrigeração. A exploração e produção de reservas naturais de hidrocarbonetos não foge a essa regra, com a dificuldade adicional de tratar complexas misturas de hidrocarbonetos, muitas vezes não bem caracterizadas, além da presença de compostos não orgânicos, como água e dióxido de carbono, empregados em técnicas para aumentar o fator de recuperação das jazidas. Na simulação numérica computacional, que usa o modelo composicional de reservatórios de hidro- carbonetos, um dos conjuntos de equações utilizado para a solução é composto pelos coeficientes de distribuição dos componentes entre as fases presentes no meio poroso. Em varios momentos da simulação uma ou mais fases podem ser constituídas de compostos puros. Nesse caso, ao invés de utilizar equações de estado, são utilizadas correlações para prever as propriedades termodinâmicas, bem como as suas derivadas (necessárias para o cálculo do jacobiano do método de Newton).
  - Objetivo geral: – Deselvolver um software que calcula as propriedades termodinâmicas de uma substância pura a partir de equações experimentais.
- Área:
  - Engenharia de reservatório.

** Título: ProjetoEngenharia-STC-3D-SimuladorDeTransferenciaDeCalor-3D
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-STC-3D-SimuladorDeTransferenciaDeCalor-3D
- Resumo:
  - Projeto de engenharia - Simulador de condução térmica em objetos 3D com perfis genéricos.
  - O seguinte projeto de engenharia deve simular a difusão térmica de qualquer objeto tridimensional, onde o usuário desenha a superfície de alguns perfis e escolhe as temperaturas e suas propriedades termofísicas.
  - A equação do Calor será modelada por diferenças finitas pelo modelo BTCS, utilizando fronteiras de Neumann, e a programação utilizará paralelismo e multithreading para acelerar as simulações.
  - No quesito prático, o usuário poderá desenhar a superfície a ser simulada, escolher sua temperatura, propriedades termofísicas e se é fonte/sumidouro ou não. Também terá a liberdade de escolher um ponto para analisar os gráficos da evolução térmica no tempo e espaço, salvar as superfícies dos perfis e carregar essas camadas com todas as suas propriedades e modificá-las. Por fim, o projeto será utilizado para estudar a injeção de calor em reservatórios 2D e 3D, e avaliar a distribuição da temperatura ao longo do tempo no reservatório.
  - Nota: Também foi o TCC do aluno Nikolas.
- Área:
  - Transferência de calor.

** Título: ProjetoEngenharia-TratamentoEstatisticoDadosGeoquimicos
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-TratamentoEstatisticoDadosGeoquimicos
- Resumo:
  - Os métodos estatísticos estão associados ao tratamento de informações. Seu emprego tem por objetivo explorar uma certa quantidade de números e extrair dos mesmos, valiosas conclusões.
  - O objetivo geral do software é propor uma série de tratamentos estatísticos como a regressão linear e os testes de hipóteses, bem como alguns testes que identificam valores anômalos (outliers).Este trabalho implementa alguns testes que identificam valores anômalos (outliers), que são: Teste do escore z modificado, Teste de Grubbs, Teste de Dixon, Teste de Cochran e Teste de Doerffel , além de testes de hipóteses e regressão linear que são aplicados em dados geoquímicos.
- Área:
  - Geoquímica.
* <<5>>Repositórios com projetos didáticos

** Título: ProjetoEngenharia-SistemaAcademico (didático)
- Link no github:
  - https://github.com/ldsc/ProjetoEngenharia-SistemaAcademico
- Resumo:
  - Mostrar o desenvolvimento de modelos UML com um exemplo administrativo conhecido dos alunos, o sistema acadêmico.

